### ISSUE TITLE
Volume mapping anomaly?

### ISSUE THREAD

**Issue by bigtfromaz** [jlesage/docker-cloudberry-backup#12]
I have this running on Synology and set it up with the GUI.  Note that the GUI is not at issue.  

However, I do see something I don't understand.  

Here is a picture of the volume mapping:

![Mapping](https://user-images.githubusercontent.com/7926086/60845127-32bb2980-a190-11e9-9d97-7246fe687aa8.PNG)
You can see that I am mapping four folders underneath /storage.  

Here is the folder selection dialog I see when selecting files and folders for backup:

![CloudBerrySelectionDialog](https://user-images.githubusercontent.com/7926086/60845397-06ec7380-a191-11e9-8265-269d6f2c6bc9.PNG)

Note that /storage is empty and the mapped shared folders are showing as peers to /storage. I expected them to be children of /storage.

Interestingly, after selecting folders, CloudBerry Backup sees it my way.  What follows is a snip of selected folders list from CloudBerry:

![CloudBerrySelectionList](https://user-images.githubusercontent.com/7926086/60845236-8a599500-a190-11e9-84b3-71bd2d4dddeb.PNG)

Note that the ones shown as peers when selecting, are in fact properly showing as children in the selected folders list.

Is this a glaring bug in CloudBerry Backup or is there something going on with the container file system, i.e. symbolic links?

**Comment by bigtfromaz** [comment]
A little more information:

In the container:

"ls /storage" displays the four file shares I mapped exactly the way I wanted with all files visible, running as root.

"ls /" includes a number of things but none of the four folders I mapped, as expected.

This appears to be a bug in CloudBerry Backup for Linux, specifically the "Backup Plan: Backup Source" dialog at the top of my issue.

I have received several identical emails from CloudBerry telling me to reach out if I have any questions.  The whole thread promising support may well be a ROBO-situation and nobody's listening.   I will attempt to take them up on their offer.  I'll try the offered route as well as trial support.

It looks to me like the inside of this container is just fine, although I would like to see bash remain installed.

I think that previous issues related to the inability to select or view file entries may be similar to ones we experienced with the CrashPlan image.  For example, permission issues and/or misunderstandings regarding how to use the -V  source:target parameter.  e.g. -v /storage:/storage .  What are the odds that all the files on the host that need to be backed up are in /storage?

I'll keep you posted.  Functionally, so far, the backup process itself seems to be pretty good, including the expeditious consumption of Azure resources.  It'll take a couple of weeks but I should get a good test with 2 TB spread across 1.3 MM files.

Tom

**Comment by jlesage** [comment]
There are issues with the way filesystem is shown in the UI.  See issue #4.
It's one of the issues I reported that never got fixed.

**Comment by bigtfromaz** [comment]
@jlesage I opened a support request.  CloudBerry asked for further information and screen snaps.  That was 24 hours ago.  If they fail to respond, I will have to find another way to backup my Synology file shares.

**Comment by bigtfromaz** [comment]
I received a response from CloudBerry Labs:  

> Your storage folder having no child folders is an expected behavior, since all child folders of storage are mount points themselves.
Tree view level shows any mounts as root nodes, we did not expect that a mount point would have only mount points as it's descendants.

I am not sure I agree with their design choice but the last sentence does explain what I am seeing.  I am using four -v parameters, each resulting in a mount point under /storage.
