### ISSUE TITLE
DNS resolving fails

### ISSUE THREAD

**Issue by Ueland** [jlesage/docker-cloudberry-backup#16]
I wonder if there are some glitches to the DNS resolving somewhere in the container and/or in the Cloudberry software?

I noticed the rather crtptic error message when doing some changes to my backup plans: "Error: can't get allowed email!"

When i checked the app logs i see the following:
```
log_worker_{0ee3a482-b479-455f-871f-ddd57818002e}_20191105123252.log:2019-11-05 12:29:27,925782 [WARN ]: [ CBC ] [ 7 ] Could not resolve host: storage.googleapis.com
log_worker_{0ee3a482-b479-455f-871f-ddd57818002e}_20191105123252.log:2019-11-05 12:29:27,925810 [WARN ]: [ CBC ] [ 7 ] Exception (curlpp::LibcurlRuntimeError): Could not resolve host: storage.googleapis.com```
```
When checking my DNS server logs, i see requests for:
```
AAAA | storage.googleapis.com.localdomain NXDOMAIN
A | storage.googleapis.com.localdomain NODATA
AAAA | storage.googleapis.com IP
A | storage.googleapis.com IP
```
resolv.conf specifies "localdomain" as a searchdomain.

I removed searchdomain from resolv.conf and it started working again, but this is all pretty standard stuff that i don`t see a reason to fail

**Comment by jlesage** [comment]
You could try to ping the address from the container to see if you have the same behavior:

```
docker exec <container name> ping storage.googleapis.com
```

**Comment by Ueland** [comment]
Thanks for the pointer. Weird that anything worked at all, because the issue was zero DNS response from the DNS server which also ran on the docker host. Fixed that and the issue got solved.
