### ISSUE TITLE
BackBlazeB2 Backup Failures

### ISSUE THREAD

**Issue by stephenpapierski** [jlesage/docker-cloudberry-backup#22]
I'm running this docker container(v1.21.2) on UNRAID (v6.8.3). I'm getting that my backup (to BackBlazeB2) completes with warnings. Logs show `SSL_write() returned SYSCALL, errno = 32`. Cloudberry support asked me for the results of `nslookup api.backblazeb2.com`.

> /tmp # nslookup 'api.backblazeb2.com'
> nslookup: can't resolve '(null)': Name does not resolve
> 
> Name:      api.backblazeb2.com
> Address 1: 206.190.215.15
> Address 2: 104.153.233.176
> Address 3: 104.153.233.180

They seem to think the result is a failure, but per [476](https://github.com/gliderlabs/docker-alpine/issues/476), this doesn't seem to indicate a problem.

I've successfully backed up over 900 GB and this is only happening to the last 50 GB or so. Any ideas?

**Comment by stephenpapierski** [comment]
I removed my upload bandwidth limits and everything completed successfully. Looks like the requests were timing out.

**Comment by stephenpapierski** [comment]
I removed my upload bandwidth limits and everything completed successfully. Looks like the requests were timing out.

**Comment by jlesage** [comment]
Great, glad to know your problem has been resolved.
