### ISSUE TITLE
unRaid V3.1.4.20

### ISSUE THREAD

**Issue by ltmichael** [jlesage/docker-cloudberry-backup#25]
Hello,

Sorry if this isn't the right place to ask this - I see the dockerfile on Github was updated to support the new version of Cloudberry 3.1.4.20. In unRaid I have the older 3.1.3 version on a fresh install. I check for updates in the GUI but none show as available. Is this something on my end or your end?

Thank you!

**Comment by jlesage** [comment]
I didn't push a new image with this CloudBerry Backup version.  I'm seeing issue with this particular version related to the license not being recognized.

**Comment by ltmichael** [comment]
Gotcha. So we'll need to wait for the next version of Cloudberry to be released so it can be testeD?

**Comment by jlesage** [comment]
See https://github.com/jlesage/docker-cloudberry-backup/issues/27 for latest news on this.
