### ISSUE TITLE
Update to 3.2.0.114

### ISSUE THREAD

**Issue by reapola** [jlesage/docker-cloudberry-backup#27]
@jlesage I see cloudberry have made 3.2.0.114 available - hasthe licence issues been resolved to allow the docker to be upgraded?

Thanks in advance!

**Comment by jlesage** [comment]
Hey sorry for the late answer on this.

I confirmed with MSP360 support team that the license issue has been fixed in 3.2.3.148.  However, this version also introduced a crash, which is also confirmed by the support team :(

So we need to wait for the next version...

**Comment by jlesage** [comment]
The latest version of CloudBerry Backup finally works.
A new Docker image is available!
